const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '    <!-- 职位分类 -->\n';
c += '    <section class="category-section">\n';
c += '      <div class="category-inner">\n';
c += '        <div class="category-grid">\n';
c += '          <aside class="category-sidebar" @mouseleave="onSidebarLeave">\n';
c += '            <div class="cat-tabs">\n';
c += "              <button class=\"cat-tab\" :class=\"{ active: activeCategoryTab === 'profession' }\" @click=\"activeCategoryTab = 'profession'; hoveredCategory = null\">按专业筛选</button>\n";
c += "              <button class=\"cat-tab\" :class=\"{ active: activeCategoryTab === 'jobtype' }\" @click=\"activeCategoryTab = 'jobtype'; hoveredCategory = null\">按职类筛选</button>\n";
c += '            </div>\n';
c += '            <div class="cat-list">\n';
c += '              <div v-for="cat in activeCategories" :key="cat.key" class="cat-item" :class="{ hovered: hoveredCategory === cat.key }" @mouseenter="onCategoryEnter(cat.key)">\n';
c += '                <div class="cat-item-left"><span class="cat-emoji">{{ cat.icon }}</span><span class="cat-name">{{ cat.label }}</span></div>\n';
c += '                <div class="cat-item-right"><span class="cat-preview">{{ cat.preview }}</span><ChevronRightIcon :size="14" /></div>\n';
c += '              </div>\n';
c += '            </div>\n';
c += '            <div class="cat-footer"><router-link to="/user/jobs" class="cat-all-link">全部专业 <ArrowRight :size="14" /></router-link></div>\n';
c += '          </aside>\n';
c += '          <div class="category-right" @mouseleave="onSubmenuLeave">\n';
c += '            <transition name="submenu-fade">\n';
c += '              <div v-if="currentSubmenu" class="submenu-panel">\n';
c += '                <h3 class="submenu-title">{{ currentSubmenu.title }}</h3>\n';
c += '                <div class="submenu-sections">\n';
c += '                  <div v-for="sec in currentSubmenu.sections" :key="sec.name" class="submenu-section">\n';
c += '                    <h4 class="submenu-section-name">{{ sec.name }}</h4>\n';
c += '                    <div class="submenu-tags">\n';
c += '                      <router-link v-for="item in sec.items" :key="item" :to="{ path: \'/user/jobs/search\', query: { q: item } }" class="submenu-tag">{{ item }}</router-link>\n';
c += '                    </div>\n';
c += '                  </div>\n';
c += '                </div>\n';
c += '              </div>\n';
c += '            </transition>\n';
c += '            <div v-show="!currentSubmenu" class="promo-banner">\n';
c += '              <div v-for="(img, i) in promoSlides" :key="i" class="promo-slide" :class="{ active: i === currentPromo }" :style="{ backgroundImage: \'url(\' + img + \')\' }" />\n';
c += '              <div class="promo-overlay" />\n';
c += '              <div class="promo-content">\n';
c += '                <h3 class="promo-title">发现更多可能</h3>\n';
c += '                <p class="promo-desc">AI 驱动的精准推荐，让好工作主动找到你</p>\n';
c += '                <router-link to="/user/jobs" class="promo-btn">立即探索 <ArrowRight :size="16" /></router-link>\n';
c += '              </div>\n';
c += '              <button class="promo-nav left" @click="prevPromo"><ChevronLeft :size="16" /></button>\n';
c += '              <button class="promo-nav right" @click="nextPromo"><ChevronRight :size="16" /></button>\n';
c += '              <div class="promo-dots">\n';
c += '                <button v-for="(_, i) in promoSlides" :key="i" class="promo-dot" :class="{ active: i === currentPromo }" @click="currentPromo = i" />\n';
c += '              </div>\n';
c += '            </div>\n';
c += '          </div>\n';
c += '        </div>\n';
c += '      </div>\n';
c += '    </section>\n\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('Categories section written: ' + c.length + ' chars');
