const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '    <!-- 统计栏 -->\n';
c += '    <section class="stats-bar">\n';
c += '      <div class="stats-inner">\n';
c += '        <div v-for="stat in stats" :key="stat.label" class="stat-item">\n';
c += '          <div class="stat-num" :data-target="stat.value" :data-suffix="stat.suffix">0</div>\n';
c += '          <div class="stat-label">{{ stat.label }}</div>\n';
c += '        </div>\n';
c += '      </div>\n';
c += '    </section>\n\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('Stats bar written: ' + c.length + ' chars');
