const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '.stats-bar { background: #1a3a5c; padding: 32px 0; }\n';
c += '.stats-inner { max-width: 1440px; margin: 0 auto; padding: 0 40px; display: flex; justify-content: space-around; }\n';
c += '.stat-item { text-align: center; }\n';
c += '.stat-num { font-size: 28px; font-weight: 700; color: #fff; font-variant-numeric: tabular-nums; }\n';
c += '.stat-label { font-size: 13px; color: rgba(255,255,255,0.6); margin-top: 4px; }\n\n';

c += '.category-section { padding: 48px 0; }\n';
c += '.category-inner { max-width: 1280px; margin: 0 auto; padding: 0 24px; }\n';
c += '.category-grid { display: grid; grid-template-columns: 300px 1fr; gap: 24px; }\n';
c += '.category-sidebar { background: #fff; border-radius: 12px; border: 1px solid #e5e7eb; box-shadow: 0 1px 4px rgba(0,0,0,0.04); overflow: hidden; }\n';
c += '.cat-tabs { display: flex; border-bottom: 1px solid #e5e7eb; }\n';
c += '.cat-tab { flex: 1; padding: 12px 0; font-size: 12px; font-weight: 700; letter-spacing: 0.5px; text-align: center; cursor: pointer; border: none; background: none; color: #909399; transition: all 0.2s; &:first-child { border-right: 1px solid #e5e7eb; } &.active { color: #1a3a5c; border-bottom: 2px solid #1a3a5c; background: rgba(26,58,92,0.03); } &:hover:not(.active) { color: #606266; } }\n';
c += '.cat-list { padding: 8px 0; }\n';
c += '.cat-item { display: flex; align-items: center; justify-content: space-between; padding: 10px 16px; cursor: pointer; transition: all 0.2s; &:hover, &.hovered { background: #f5f7fa; } }\n';
c += '.cat-item-left { display: flex; align-items: center; gap: 10px; }\n';
c += '.cat-emoji { font-size: 16px; }\n';
c += '.cat-name { font-size: 14px; font-weight: 500; color: #303133; }\n';
c += '.cat-item-right { display: flex; align-items: center; gap: 4px; }\n';
c += '.cat-preview { font-size: 12px; color: #c0c4cc; }\n';
c += '.cat-footer { padding: 12px; border-top: 1px solid #e5e7eb; text-align: center; }\n';
c += '.cat-all-link { font-size: 14px; font-weight: 600; color: #1a3a5c; text-decoration: none; display: inline-flex; align-items: center; gap: 4px; &:hover { color: #0ea5e9; text-decoration: none; } }\n\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('CSS stats+category written: ' + c.length + ' chars');
