const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '    <!-- 英雄区 -->\n';
c += '    <section class="hero-section">\n';
c += '      <div class="carousel">\n';
c += '        <div v-for="(img, i) in heroSlides" :key="i" class="slide" :class="{ active: i === currentSlide }" :style="{ backgroundImage: \url(\)\ }" />\n';
c += '        <div class="carousel-overlay" />\n';
c += '      </div>\n';
c += '      <button class="carousel-btn left" @click="prevSlide"><ChevronLeft :size="22" /></button>\n';
c += '      <button class="carousel-btn right" @click="nextSlide"><ChevronRight :size="22" /></button>\n';
c += '      <div class="carousel-dots">\n';
c += '        <button v-for="(_, i) in heroSlides" :key="i" class="dot" :class="{ active: i === currentSlide }" @click="goToSlide(i)" />\n';
c += '      </div>\n';
c += '      <div class="hero-content">\n';
c += '        <h1 class="hero-title hero-anim">成就你的非凡未来</h1>\n';
c += '        <p class="hero-subtitle hero-anim">触达最具影响力的科技职位、AI 精准匹配，让每位人才找到理想舞台。</p>\n';
c += '        <div class="search-bar hero-anim">\n';
c += '          <div class="search-field"><Briefcase :size="18" class="search-icon" /><input v-model="searchKeyword" type="text" placeholder="搜索职位、公司或关键词" @keydown.enter="handleSearch" /></div>\n';
c += '          <div class="search-divider" />\n';
c += '          <div class="search-field"><MapPin :size="18" class="search-icon" /><input v-model="searchCity" type="text" placeholder="城市" @keydown.enter="handleSearch" /></div>\n';
c += '          <button class="search-btn" @click="handleSearch"><Search :size="18" /> 搜索</button>\n';
c += '        </div>\n';
c += '        <div class="hot-tags hero-anim">\n';
c += '          <span class="tag-label">热门：</span>\n';
c += '          <button class="hot-tag" @click="searchKeyword = \'前端开发\'; handleSearch()">前端开发</button>\n';
c += '          <button class="hot-tag" @click="searchKeyword = \'AI 算法\'; handleSearch()">AI 算法</button>\n';
c += '          <button class="hot-tag" @click="searchKeyword = \'Java\'; handleSearch()">Java</button>\n';
c += '          <button class="hot-tag" @click="searchKeyword = \'数据分析\'; handleSearch()">数据分析</button>\n';
c += '        </div>\n';
c += '      </div>\n';
c += '    </section>\n\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('Hero template written: ' + c.length + ' chars');
