const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '<style scoped lang=\"scss\">\n';
c += '.home-page { min-height: 100vh; background: #f8f9fb; }\n\n';
c += '.reveal { opacity: 0; transform: translateY(30px); transition: opacity 0.6s cubic-bezier(0.22,1,0.36,1), transform 0.6s cubic-bezier(0.22,1,0.36,1); }\n';
c += '.reveal.revealed { opacity: 1; transform: translateY(0); }\n\n';
c += '@keyframes heroUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }\n';
c += '.hero-anim { opacity: 0; animation: heroUp 0.6s cubic-bezier(0.22,1,0.36,1) forwards; }\n';
c += '.hero-anim:nth-child(1) { animation-delay: 0.2s; }\n';
c += '.hero-anim:nth-child(2) { animation-delay: 0.35s; }\n';
c += '.hero-anim:nth-child(3) { animation-delay: 0.5s; }\n';
c += '.hero-anim:nth-child(4) { animation-delay: 0.6s; }\n\n';
c += '.top-nav { position: fixed; top: 0; left: 0; right: 0; z-index: 100; height: 56px; background: #fff; border-bottom: 1px solid #e5e7eb; }\n';
c += '.nav-inner { max-width: 1440px; margin: 0 auto; height: 100%; display: flex; align-items: center; justify-content: space-between; padding: 0 40px; }\n';
c += '.nav-logo { font-size: 22px; font-weight: 700; color: #1a3a5c; text-decoration: none; &:hover { text-decoration: none; } }\n';
c += '.nav-links { display: flex; gap: 28px; }\n';
c += '.nav-link { font-size: 13px; font-weight: 500; color: #606266; text-decoration: none; padding-bottom: 2px; border-bottom: 2px solid transparent; transition: all 0.2s; &:hover, &.active { color: #1a3a5c; border-bottom-color: #1a3a5c; text-decoration: none; } }\n';
c += '.nav-actions { display: flex; align-items: center; gap: 12px; }\n';
c += '.icon-btn { width: 36px; height: 36px; display: flex; align-items: center; justify-content: center; border-radius: 8px; color: #606266; transition: all 0.2s; &:hover { background: #f5f7fa; color: #1a3a5c; } }\n';
c += '.user-badge { display: flex; align-items: center; gap: 8px; cursor: pointer; padding: 4px 8px; border-radius: 8px; transition: background 0.2s; &:hover { background: #f5f7fa; } }\n';
c += '.avatar { width: 30px; height: 30px; border-radius: 50%; background: #1a3a5c; color: #fff; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 700; }\n';
c += '.username { font-size: 13px; font-weight: 500; color: #303133; }\n';
c += '.nav-text-btn { font-size: 13px; font-weight: 500; color: #1a3a5c; text-decoration: none; padding: 6px 12px; border-radius: 6px; transition: background 0.2s; &:hover { background: #f5f7fa; } }\n';
c += '.nav-primary-btn { font-size: 13px; font-weight: 600; color: #fff; text-decoration: none; padding: 6px 18px; border-radius: 999px; background: #1a3a5c; transition: all 0.2s; &:hover { background: #24507a; } }\n\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('CSS part 1 written: ' + c.length + ' chars');
