const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '.category-right { position: relative; min-height: 400px; border-radius: 12px; overflow: hidden; }\n';
c += '.submenu-panel { position: absolute; inset: 0; z-index: 20; background: #fff; border-radius: 12px; border: 1px solid #e5e7eb; box-shadow: 0 8px 32px rgba(0,0,0,0.08); padding: 28px; overflow-y: auto; }\n';
c += '.submenu-fade-enter-active { transition: opacity 0.25s ease; }\n';
c += '.submenu-fade-leave-active { transition: opacity 0.15s ease; }\n';
c += '.submenu-fade-enter-from, .submenu-fade-leave-to { opacity: 0; }\n';
c += '.submenu-title { font-size: 18px; font-weight: 700; color: #303133; margin-bottom: 24px; }\n';
c += '.submenu-sections { display: flex; flex-direction: column; gap: 20px; }\n';
c += '.submenu-section-name { font-size: 13px; font-weight: 700; color: #1a3a5c; margin-bottom: 10px; letter-spacing: 0.3px; }\n';
c += '.submenu-tags { display: flex; flex-wrap: wrap; gap: 8px; }\n';
c += '.submenu-tag { padding: 6px 14px; border-radius: 6px; background: #f5f7fa; font-size: 13px; color: #606266; text-decoration: none; transition: all 0.2s; &:hover { background: #1a3a5c; color: #fff; } }\n\n';

c += '.promo-banner { position: relative; height: 100%; min-height: 400px; border-radius: 12px; overflow: hidden; }\n';
c += '.promo-slide { position: absolute; inset: 0; background-size: cover; background-position: center; opacity: 0; transition: opacity 0.8s ease-in-out; &.active { opacity: 1; } }\n';
c += '.promo-overlay { position: absolute; inset: 0; z-index: 1; background: linear-gradient(135deg, rgba(26,58,92,0.85) 0%, rgba(14,165,233,0.3) 100%); }\n';
c += '.promo-content { position: absolute; inset: 0; z-index: 2; display: flex; flex-direction: column; justify-content: center; padding: 48px; }\n';
c += '.promo-title { font-size: 32px; font-weight: 700; color: #fff; margin-bottom: 12px; }\n';
c += '.promo-desc { font-size: 16px; color: rgba(255,255,255,0.8); margin-bottom: 24px; max-width: 360px; line-height: 1.6; }\n';
c += '.promo-btn { display: inline-flex; align-items: center; gap: 8px; padding: 12px 32px; border-radius: 999px; background: #fff; color: #1a3a5c; font-size: 15px; font-weight: 600; text-decoration: none; box-shadow: 0 4px 16px rgba(0,0,0,0.12); transition: all 0.25s; width: fit-content; &:hover { transform: translateY(-2px); box-shadow: 0 8px 24px rgba(0,0,0,0.16); text-decoration: none; } }\n';
c += '.promo-nav { position: absolute; top: 50%; transform: translateY(-50%); z-index: 10; width: 36px; height: 36px; border-radius: 50%; border: 1px solid rgba(255,255,255,0.25); background: rgba(255,255,255,0.15); backdrop-filter: blur(8px); color: #fff; cursor: pointer; display: flex; align-items: center; justify-content: center; transition: all 0.25s; &:hover { background: rgba(255,255,255,0.3); } &.left { left: 16px; } &.right { right: 16px; } }\n';
c += '.promo-dots { position: absolute; bottom: 16px; left: 50%; transform: translateX(-50%); z-index: 10; display: flex; gap: 6px; }\n';
c += '.promo-dot { width: 6px; height: 6px; border-radius: 999px; border: none; background: rgba(255,255,255,0.4); cursor: pointer; transition: all 0.3s; &.active { background: #fff; width: 18px; } }\n\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('CSS submenu+promo written: ' + c.length + ' chars');
