const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '<script setup lang="ts">\n';
c += 'import { ref, computed, onMounted, onUnmounted, nextTick } from "vue"\n';
c += 'import { useRouter } from "vue-router"\n';
c += 'import { useAuthStore } from "@/store/auth"\n';
c += 'import { useScrollReveal } from "@/composables/useScrollReveal"\n';
c += 'import {\n';
c += '  Search, MapPin, ChevronLeft, ChevronRight, Briefcase, Bell, ArrowRight,\n';
c += '  Network, Sparkles, Route, ChevronRightIcon,\n';
c += "} from 'lucide-vue-next'\n\n";
c += 'const router = useRouter()\n';
c += 'const authStore = useAuthStore()\n';
c += 'const page = ref()\n';
c += 'useScrollReveal(page)\n\n';
fs.writeFileSync(p, c, 'utf-8');
console.log("Part 1 done: " + c.length + " chars");
