const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '@media (max-width: 1024px) {\n';
c += '  .nav-links { display: none; } .hero-title { font-size: 32px; }\n';
c += '  .category-grid { grid-template-columns: 1fr; } .category-sidebar { max-height: 320px; overflow-y: auto; }\n';
c += '  .jobs-grid { grid-template-columns: 1fr 1fr; } .features-grid { grid-template-columns: 1fr; } .footer-links { gap: 40px; }\n';
c += '}\n';
c += '@media (max-width: 640px) {\n';
c += '  .hero-section { height: 70vh; } .hero-title { font-size: 26px; } .hero-subtitle { font-size: 15px; }\n';
c += '  .search-bar { flex-direction: column; } .search-divider { display: none; }\n';
c += '  .jobs-grid { grid-template-columns: 1fr; }\n';
c += '  .footer-links { flex-direction: column; gap: 24px; } .footer-bottom { flex-direction: column; gap: 8px; }\n';
c += '  .stats-inner { flex-wrap: wrap; gap: 16px; } .stat-item { width: 45%; }\n';
c += '}\n';
c += '</style>\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('CSS responsive written: ' + c.length + ' chars');
