const fs = require('fs');
const p = "C:\\Users\\Administrator\\Desktop\\Zhihire-StarMap\\frontend\\src\\views\\common\\HomeView.vue";
let c = '';
c += '<template>\n';
c += '  <div ref="page" class="home-page">\n';
c += '    <!-- 导航栏 -->\n';
c += '    <nav class="top-nav">\n';
c += '      <div class="nav-inner">\n';
c += '        <router-link to="/" class="nav-logo">智聘星图</router-link>\n';
c += '        <div class="nav-links">\n';
c += '          <router-link to="/" class="nav-link" :class="{ active: .path === \'/\' }">探索</router-link>\n';
c += '          <router-link to="/user/jobs" class="nav-link">职位推荐</router-link>\n';
c += '          <router-link to="/user/jobs/search" class="nav-link">职位搜索</router-link>\n';
c += '          <router-link to="/user/ability-map" class="nav-link">能力图谱</router-link>\n';
c += '          <router-link to="/user/career-plan" class="nav-link">职业规划</router-link>\n';
c += '          <router-link to="/user/resume" class="nav-link">简历中心</router-link>\n';
c += '          <router-link to="/user/interview" class="nav-link">面试功能</router-link>\n';
c += '          <router-link to="/user/social" class="nav-link">社交</router-link>\n';
c += '        </div>\n';
c += '        <div class="nav-actions">\n';
c += '          <template v-if="authStore.isLoggedIn">\n';
c += '            <router-link to="/user/notifications" class="icon-btn"><Bell :size="18" /></router-link>\n';
c += '            <el-dropdown>\n';
c += '              <div class="user-badge"><div class="avatar">{{ authStore.username?.charAt(0).toUpperCase() }}</div><span class="username">{{ authStore.username }}</span></div>\n';
c += '              <template #dropdown>\n';
c += '                <el-dropdown-menu>\n';
c += '                  <el-dropdown-item @click="goDashboard">进入工作台</el-dropdown-item>\n';
c += '                  <el-dropdown-item divided @click="authStore.logout(); router.push(\'/\')">退出登录</el-dropdown-item>\n';
c += '                </el-dropdown-menu>\n';
c += '              </template>\n';
c += '            </el-dropdown>\n';
c += '          </template>\n';
c += '          <template v-else>\n';
c += '            <router-link to="/login" class="nav-text-btn">登录</router-link>\n';
c += '            <router-link to="/register" class="nav-primary-btn">注册</router-link>\n';
c += '          </template>\n';
c += '        </div>\n';
c += '      </div>\n';
c += '    </nav>\n\n';
fs.appendFileSync(p, c, 'utf-8');
console.log('Nav template written: ' + c.length + ' chars');
