f = open(r'C:\Users\Administrator\Desktop\Zhihire-StarMap\frontend\src\views\common\HomeView.vue', 'a', encoding='utf-8')
f.write('\nconst currentSubmenu = computed(() => hoveredCategory.value ? submenuData[hoveredCategory.value] : None)\n')
f.write('function onCategoryEnter(key) { hoveredCategory.value = key }\n')
f.write('function onSidebarLeave() {\n')
f.write('  setTimeout(() => {\n')
f.write("    if (!document.querySelector('.submenu-panel:hover') && !document.querySelector('.category-sidebar:hover'))\n")
f.write('      hoveredCategory.value = None\n')
f.write('  }, 100)\n')
f.write('}\n')
f.write('function onSubmenuLeave() { hoveredCategory.value = None }\n\n')

f.write('const featuredJobs = [\n')
f.write('  { title: "高级前端工程师", company: "银河麒麟", city: "北京", salary: "25-40K", tags: ["Vue", "TypeScript", "Element Plus"] },\n')
f.write('  { title: "AI 算法工程师", company: "DeepSeek", city: "杭州", salary: "35-60K", tags: ["Python", "NLP", "大模型"] },\n')
f.write('  { title: "Java 后端开发", company: "人大金仓", city: "北京", salary: "20-35K", tags: ["Spring Boot", "MyBatis", "KingbaseES"] },\n')
f.write('  { title: "数据分析师", company: "华为", city: "深圳", salary: "22-38K", tags: ["SQL", "Python", "ECharts"] },\n')
f.write('  { title: "嵌入式开发工程师", company: "龙芯中科", city: "北京", salary: "20-35K", tags: ["C/C++", "LoongArch", "Linux"] },\n')
f.write('  { title: "全栈工程师", company: "统信软件", city: "武汉", salary: "18-30K", tags: ["Vue", "Node.js", "PostgreSQL"] },\n')
f.write(']\n\n')

f.write('const stats = [\n')
f.write('  { value: 12000, suffix: "+", label: "活跃职位" },\n')
f.write('  { value: 8500, suffix: "+", label: "注册企业" },\n')
f.write('  { value: 45000, suffix: "+", label: "求职者" },\n')
f.write('  { value: 98, suffix: "%", label: "匹配满意度" },\n')
f.write(']\n')
f.write('const statsStarted = ref(False)\n')
f.write('let statsObserver = None\n\n')

f.write('function animateCounters() {\n')
f.write('  if (statsStarted.value) return\n')
f.write('  statsStarted.value = True\n')
f.write('  document.querySelectorAll(".stat-num").forEach((el) => {\n')
f.write("    const target = parseInt(el.dataset.target or '0', 10)\n")
f.write("    const suffix = el.dataset.suffix or ''\n")
f.write('    const duration = 1200\n')
f.write('    const start = performance.now()\n')
f.write('    function tick(now) {\n')
f.write('      const progress = Math.min((now - start) / duration, 1)\n')
f.write('      const eased = 1 - Math.pow(1 - progress, 3)\n')
f.write('      el.textContent = Math.floor(eased * target).toLocaleString() + suffix\n')
f.write('      if (progress < 1) requestAnimationFrame(tick)\n')
f.write('    }\n')
f.write('    requestAnimationFrame(tick)\n')
f.write('  })\n')
f.write('}\n\n')
f.close()
print('Done: featured jobs, stats')
