import os

base = r'C:\Users\Administrator\Desktop\Zhihire-StarMap\backend\app\models\schemas'
p = os.path.join(base, 'company.py')

content = '\"\"\"' + chr(20225) + chr(19994) + chr(27169) + ' Pydantic ' + chr(35831) + chr(27714) + '/' + chr(21709) + chr(24212) + chr(27169) + chr(22411) + '.' + '\n'
content += '\n'
content += chr(21253) + chr(21547) + chr(20225) + chr(19994) + chr(20449) + chr(24687) + chr(26597) + chr(35810) + ',' + chr(26356) + chr(26032) + ',' + 'Dashboard ' + chr(39318) + chr(39029) + chr(32479) + chr(35745) + chr(30340) + chr(35831) + chr(27714) + chr(19982) + chr(21709) + chr(24212) + chr(27169) + chr(22411) + '.' + '\n'
content += '\"\"\"' + '\n'
content += 'from datetime import datetime' + '\n'
content += '' + '\n'
content += 'from pydantic import BaseModel, ConfigDict, Field' + '\n'
content += '' + '\n'
content += '' + '\n'
content += '# ========== ' + chr(21709) + chr(24212) + chr(27169) + chr(22411) + ' ==========' + '\n'
content += '' + '\n'
content += '' + '\n'
content += 'class CompanyInfoResponse(BaseModel):' + '\n'
content += '    ' + '\"\"\"' + chr(20225) + chr(19994) + chr(20449) + chr(24687) + chr(21709) + chr(24212) + chr(27169) + chr(22411) + '.' + '\"\"\"' + '\n'
content += '    model_config = ConfigDict(from_attributes=True)' + '\n'
content += '' + '\n'
content += '    id: int' + '\n'
content += '    company_name: str' + '\n'
content += '    industry: str | None = None' + '\n'
content += '    scale: str | None = None' + '\n'
content += '    website: str | None = None' + '\n'
content += '    logo_url: str | None = None' + '\n'
content += '    description: str | None = None' + '\n'
content += '    address: str | None = None' + '\n'
content += '    contact_name: str | None = None' + '\n'
content += '    contact_phone: str | None = None' + '\n'
content += '    contact_email: str | None = None' + '\n'
content += '    audit_status: str' + '\n'
content += '    audit_reason: str | None = None' + '\n'
content += '    created_at: datetime' + '\n'
content += '    updated_at: datetime' + '\n'
content += '' + '\n'
content += '' + '\n'
content += 'class DashboardJobItem(BaseModel):' + '\n'
content += '    ' + '\"\"\"' + 'Dashboard ' + chr(26368) + chr(36817) + chr(23703) + chr(20301) + chr(39033) + '.' + '\"\"\"' + '\n'
content += '    model_config = ConfigDict(from_attributes=True)' + '\n'
content += '' + '\n'
content += '    id: int' + '\n'
content += '    title: str' + '\n'
content += '    status: str' + '\n'
content += '    city: str | None = None' + '\n'
content += '    salary_min: float | None = None' + '\n'
content += '    salary_max: float | None = None' + '\n'
content += '    job_type: str' + '\n'
content += '    views: int' + '\n'
content += '    created_at: datetime' + '\n'
content += '' + '\n'
content += '' + '\n'
content += 'class DashboardApplicationItem(BaseModel):' + '\n'
content += '    ' + '\"\"\"' + 'Dashboard ' + chr(26368) + chr(36817) + chr(25237) + chr(36882) + chr(39033) + '.' + '\"\"\"' + '\n'
content += '    model_config = ConfigDict(from_attributes=True)' + '\n'
content += '' + '\n'
content += '    id: int' + '\n'
content += '    job_id: int' + '\n'
content += '    job_title: str | None = None' + '\n'
content += '    user_id: int' + '\n'
content += '    applicant_name: str | None = None' + '\n'
content += '    status: str' + '\n'
content += '    created_at: datetime' + '\n'
content += '' + '\n'
content += '' + '\n'
content += 'class DashboardStats(BaseModel):' + '\n'
content += '    ' + '\"\"\"' + 'Dashboard ' + chr(32479) + chr(35745) + chr(25968) + chr(23383) + '.' + '\"\"\"' + '\n'
content += '    total_jobs: int = 0' + '\n'
content += '    active_jobs: int = 0' + '\n'
content += '    total_applications: int = 0' + '\n'
content += '' + '\n'
content += '' + '\n'
content += 'class CompanyDashboardResponse(BaseModel):' + '\n'
content += '    ' + '\"\"\"' + chr(20225) + chr(19994) + chr(39318) + chr(39029) + ' Dashboard ' + chr(21709) + chr(24212) + chr(27169) + chr(22411) + '.' + '\"\"\"' + '\n'
content += '    stats: DashboardStats' + '\n'
content += '    recent_jobs: list[DashboardJobItem] = []' + '\n'
content += '    recent_applications: list[DashboardApplicationItem] = []' + '\n'
content += '' + '\n'
content += '' + '\n'
content += 'class CompanyUpdateRequest(BaseModel):' + '\n'
content += '    ' + '\"\"\"' + chr(32534) + chr(36753) + chr(20225) + chr(19994) + chr(20449) + chr(24687) + chr(35831) + chr(27714) + '(' + chr(25152) + chr(26377) + chr(23383) + chr(27425) + chr(36873) + chr(39033) + ')' + '.' + '\n'
content += '    ' + chr(26356) + chr(26032) + chr(21518) + ' audit_status ' + chr(23558) + chr(33258) + chr(21160) + chr(37325) + chr(32622) + chr(20026) + ' PENDING' + chr(65292) + chr(38656) + chr(37325) + chr(26032) + chr(23457) + chr(26680) + '.' + '\n'
content += '    ' + '\"\"\"' + '\n'
content += '    company_name: str | None = Field(None, max_length=200)' + '\n'
content += '    industry: str | None = Field(None, max_length=100)' + '\n'
content += '    scale: str | None = Field(None, max_length=50)' + '\n'
content += '    website: str | None = Field(None, max_length=500)' + '\n'
content += '    logo_url: str | None = Field(None, max_length=500)' + '\n'
content += '    description: str | None = None' + '\n'
content += '    address: str | None = Field(None, max_length=500)' + '\n'
content += '    contact_name: str | None = Field(None, max_length=50)' + '\n'
content += '    contact_phone: str | None = Field(None, max_length=20)' + '\n'
content += '    contact_email: str | None = Field(None, max_length=100)' + '\n'

with open(p, 'w', encoding='utf-8') as f:
    f.write(content)
print('Written: company.py')
