"""add_major_and_job_category

Revision ID: 4866ad7374ed
Revises: cdd9ea314360
Create Date: 2026-07-08 18:22:06.140360+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4866ad7374ed'
down_revision: Union[str, None] = 'cdd9ea314360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_login_log_user_id'), table_name='login_log')
    op.drop_table('login_log')
    op.drop_index(op.f('idx_ors_role_id'), table_name='occupation_role_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_ors_skill_id'), table_name='occupation_role_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('occupation_role_skill')
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('idx_ai_chat_module'), table_name='ai_chat_history', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_ai_chat_user_id'), table_name='ai_chat_history', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('ai_chat_history')
    op.drop_index(op.f('idx_ai_provider_name'), table_name='ai_provider')
    op.create_index(op.f('ix_ai_provider_provider_name'), 'ai_provider', ['provider_name'], unique=True)
    op.alter_column('career_plan', 'target_role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('career_plan', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='规划来源：INTERVIEW/PROACTIVE/RECOMMEND',
               existing_server_default=sa.text("'PROACTIVE'::character varying"))
    op.drop_index(op.f('idx_career_plan_user_id'), table_name='career_plan', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_career_plan_user_id'), 'career_plan', ['user_id'], unique=False)
    op.drop_table_comment(
        'career_plan',
        existing_comment='职业规划',
        schema=None
    )
    op.alter_column('company', 'audit_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='审核状态：UNVERIFIED/PENDING/VERIFIED/REJECTED',
               existing_nullable=False,
               existing_server_default=sa.text("'UNVERIFIED'::character varying"))
    op.drop_index(op.f('idx_company_audit_status'), table_name='company', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_company_user_id'), table_name='company', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_company_user_id'), 'company', ['user_id'], unique=True)
    op.create_foreign_key(None, 'company', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'company',
        existing_comment='企业档案',
        schema=None
    )
    op.alter_column('interview_answer', 'ai_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='AI 评分 0~100',
               existing_nullable=True)
    op.drop_index(op.f('idx_interview_answer_question'), table_name='interview_answer', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_interview_answer_question_id'), 'interview_answer', ['question_id'], unique=False)
    op.drop_table_comment(
        'interview_answer',
        existing_comment='用户面试回答',
        schema=None
    )
    op.alter_column('interview_question', 'question_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               comment=None,
               existing_comment='题型：TECHNICAL/BEHAVIORAL/SITUATIONAL/RESUME_BASED',
               existing_nullable=False)
    op.alter_column('interview_question', 'is_bank_visible',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='报告完成后是否题库可见',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_interview_question_session'), table_name='interview_question', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_interview_question_session_id'), 'interview_question', ['session_id'], unique=False)
    op.drop_table_comment(
        'interview_question',
        existing_comment='面试问题',
        schema=None
    )
    op.alter_column('interview_report', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='综合评分 0~100',
               existing_nullable=True)
    op.alter_column('interview_report', 'radar',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='五维雷达：communication/technical/problem_solving/culture_fit/depth',
               existing_nullable=True)
    op.drop_index(op.f('idx_interview_report_session'), table_name='interview_report', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_interview_report_session_id'), 'interview_report', ['session_id'], unique=True)
    op.drop_table_comment(
        'interview_report',
        existing_comment='面试报告',
        schema=None
    )
    op.alter_column('interview_session', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='会话状态：PENDING/IN_PROGRESS/COMPLETED/ABORTED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_index(op.f('idx_interview_session_job_id'), table_name='interview_session', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_interview_session_status'), table_name='interview_session', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_interview_session_user_id'), table_name='interview_session', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_interview_session_user_id'), 'interview_session', ['user_id'], unique=False)
    op.drop_table_comment(
        'interview_session',
        existing_comment='面试会话',
        schema=None
    )
    op.add_column('job', sa.Column('major', sa.String(length=200), nullable=True))
    op.add_column('job', sa.Column('job_category', sa.String(length=100), nullable=True))
    op.alter_column('job', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='岗位来源：MANUAL手动/UPLOAD文件上传',
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.alter_column('job', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='岗位状态：OPEN/CLOSED/DRAFT',
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.drop_index(op.f('idx_job_city'), table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_job_company_id'), table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_job_occupation_role_id'), table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_job_status'), table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_job_company_id'), 'job', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_occupation_role_id'), 'job', ['occupation_role_id'], unique=False)
    op.create_foreign_key(None, 'job', 'occupation_role', ['occupation_role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'job', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'job',
        existing_comment='岗位表',
        schema=None
    )
    op.alter_column('job_skill', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment=None,
               existing_comment='重要度 1~5',
               existing_server_default=sa.text('3'))
    op.alter_column('job_skill', 'required_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='要求等级：MUST/NICE/BONUS',
               existing_server_default=sa.text("'NICE'::character varying"))
    op.drop_index(op.f('idx_job_skill_job_id'), table_name='job_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_job_skill_skill_id'), table_name='job_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_job_skill_job_id'), 'job_skill', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_skill_skill_id'), 'job_skill', ['skill_id'], unique=False)
    op.create_foreign_key(None, 'job_skill', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_skill', 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'job_skill',
        existing_comment='岗位技能关联',
        schema=None
    )
    op.alter_column('match_result', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_match_result_job_id'), table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_match_result_resume_id'), table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_match_result_resume_job'), table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_match_result_score'), table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_match_result_job_id'), 'match_result', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_result_resume_id'), 'match_result', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'match_result', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'match_result', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'match_result',
        existing_comment='匹配结果（懒计算 + 新鲜度缓存）',
        schema=None
    )
    op.alter_column('notification', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notification', 'type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='通知类型：APPLICATION/INTERVIEW_INVITE/SYSTEM',
               existing_nullable=False,
               existing_server_default=sa.text("'SYSTEM'::character varying"))
    op.drop_index(op.f('idx_notification_is_read'), table_name='notification', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_notification_type'), table_name='notification', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_notification_user_id'), table_name='notification', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.drop_table_comment(
        'notification',
        existing_comment='通知表',
        schema=None
    )
    op.create_index(op.f('ix_occupation_role_name'), 'occupation_role', ['name'], unique=True)
    op.drop_table_comment(
        'occupation_role',
        existing_comment='职业角色（后端开发/前端开发/测试工程师等）',
        schema=None
    )
    op.drop_index(op.f('idx_operation_log_module'), table_name='operation_log')
    op.drop_index(op.f('idx_operation_log_user_id'), table_name='operation_log')
    op.create_index(op.f('ix_operation_log_user_id'), 'operation_log', ['user_id'], unique=False)
    op.drop_table_comment(
        'operation_log',
        existing_comment='操作日志（AOP @OperationLog 落库）',
        schema=None
    )
    op.alter_column('parse_task', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务状态：WAITING/PARSING/SUCCESS/FAILED/REJECTED',
               existing_nullable=False,
               existing_server_default=sa.text("'WAITING'::character varying"))
    op.drop_index(op.f('idx_parse_task_file_id'), table_name='parse_task', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_parse_task_status'), table_name='parse_task', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_parse_task_user_id'), table_name='parse_task', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_parse_task_file_id'), 'parse_task', ['file_id'], unique=False)
    op.create_index(op.f('ix_parse_task_user_id'), 'parse_task', ['user_id'], unique=False)
    op.drop_table_comment(
        'parse_task',
        existing_comment='文档解析任务',
        schema=None
    )
    op.alter_column('recommend_record', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recommend_record', 'is_clicked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('recommend_record', 'is_applied',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('recommend_record', 'is_invited',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_recommend_job_id'), table_name='recommend_record', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_recommend_user_id'), table_name='recommend_record', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_recommend_record_job_id'), 'recommend_record', ['job_id'], unique=False)
    op.create_index(op.f('ix_recommend_record_user_id'), 'recommend_record', ['user_id'], unique=False)
    op.create_foreign_key(None, 'recommend_record', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recommend_record', 'resume', ['resume_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recommend_record', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'recommend_record',
        existing_comment='推荐记录',
        schema=None
    )
    op.drop_index(op.f('idx_resume_file_id'), table_name='resume', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_resume_user_id'), table_name='resume', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.drop_table_comment(
        'resume',
        existing_comment='简历实体',
        schema=None
    )
    op.drop_index(op.f('idx_resume_opt_job_id'), table_name='resume_optimization', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_resume_opt_resume_id'), table_name='resume_optimization', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_resume_optimization_resume_id'), 'resume_optimization', ['resume_id'], unique=False)
    op.drop_table_comment(
        'resume_optimization',
        existing_comment='简历优化建议',
        schema=None
    )
    op.alter_column('skill', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='技能领域：后端/前端/测试/运维/数据/通用',
               existing_nullable=True)
    op.alter_column('skill', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='技能状态：ACTIVE/CANDIDATE/MERGED',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.drop_index(op.f('idx_skill_name'), table_name='skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=True)
    op.drop_table_comment(
        'skill',
        existing_comment='技能字典',
        schema=None
    )
    op.drop_index(op.f('idx_skill_synonym_skill_id'), table_name='skill_synonym', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_skill_synonym_synonym'), table_name='skill_synonym', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_skill_synonym_skill_id'), 'skill_synonym', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_synonym_synonym'), 'skill_synonym', ['synonym'], unique=False)
    op.create_foreign_key(None, 'skill_synonym', 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'skill_synonym',
        existing_comment='技能同义词（支撑三态合并）',
        schema=None
    )
    op.drop_index(op.f('idx_upload_file_uploader'), table_name='upload_file')
    op.create_index(op.f('ix_upload_file_uploader_id'), 'upload_file', ['uploader_id'], unique=False)
    op.drop_table_comment(
        'upload_file',
        existing_comment='文件本体表（单一事实源）',
        schema=None
    )
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='用户角色：ADMIN/USER/COMPANY',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='账户状态：NORMAL/DISABLED/BANNED',
               existing_nullable=False,
               existing_server_default=sa.text("'NORMAL'::character varying"))
    op.alter_column('user', 'deleted_at',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='逻辑删除标记：0未删/1已删',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::character varying"))
    op.drop_index(op.f('idx_user_role'), table_name='user', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_user_status'), table_name='user', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_user_username'), table_name='user', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table_comment(
        'user',
        existing_comment='用户主表',
        schema=None
    )
    op.alter_column('user_profile', 'profile_completeness',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='简历完成度 0~100',
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_user_profile_user_id'), table_name='user_profile', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_foreign_key(None, 'user_profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'user_profile',
        existing_comment='求职者档案',
        schema=None
    )
    op.alter_column('user_skill', 'proficiency_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_user_skill_skill_id'), table_name='user_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index(op.f('idx_user_skill_user_id'), table_name='user_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('ix_user_skill_skill_id'), 'user_skill', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skill_user_id'), 'user_skill', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_skill', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_skill', 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'user_skill',
        existing_comment='用户技能关联',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_skill',
        '用户技能关联',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'user_skill', type_='foreignkey')
    op.drop_constraint(None, 'user_skill', type_='foreignkey')
    op.drop_index(op.f('ix_user_skill_user_id'), table_name='user_skill')
    op.drop_index(op.f('ix_user_skill_skill_id'), table_name='user_skill')
    op.create_index(op.f('idx_user_skill_user_id'), 'user_skill', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_user_skill_skill_id'), 'user_skill', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('user_skill', 'proficiency_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'user_profile',
        '求职者档案',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.create_index(op.f('idx_user_profile_user_id'), 'user_profile', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('user_profile', 'profile_completeness',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='简历完成度 0~100',
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'user',
        '用户主表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('idx_user_username'), 'user', ['username'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_user_status'), 'user', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_user_role'), 'user', ['role'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('user', 'deleted_at',
               existing_type=sa.VARCHAR(length=1),
               comment='逻辑删除标记：0未删/1已删',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='账户状态：NORMAL/DISABLED/BANNED',
               existing_nullable=False,
               existing_server_default=sa.text("'NORMAL'::character varying"))
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='用户角色：ADMIN/USER/COMPANY',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_table_comment(
        'upload_file',
        '文件本体表（单一事实源）',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_upload_file_uploader_id'), table_name='upload_file')
    op.create_index(op.f('idx_upload_file_uploader'), 'upload_file', ['uploader_id'], unique=False)
    op.create_table_comment(
        'skill_synonym',
        '技能同义词（支撑三态合并）',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'skill_synonym', type_='foreignkey')
    op.drop_index(op.f('ix_skill_synonym_synonym'), table_name='skill_synonym')
    op.drop_index(op.f('ix_skill_synonym_skill_id'), table_name='skill_synonym')
    op.create_index(op.f('idx_skill_synonym_synonym'), 'skill_synonym', ['synonym'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_skill_synonym_skill_id'), 'skill_synonym', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table_comment(
        'skill',
        '技能字典',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.create_index(op.f('idx_skill_name'), 'skill', ['name'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('skill', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='技能状态：ACTIVE/CANDIDATE/MERGED',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('skill', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='技能领域：后端/前端/测试/运维/数据/通用',
               existing_nullable=True)
    op.create_table_comment(
        'resume_optimization',
        '简历优化建议',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_resume_optimization_resume_id'), table_name='resume_optimization')
    op.create_index(op.f('idx_resume_opt_resume_id'), 'resume_optimization', ['resume_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_resume_opt_job_id'), 'resume_optimization', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table_comment(
        'resume',
        '简历实体',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.create_index(op.f('idx_resume_user_id'), 'resume', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_resume_file_id'), 'resume', ['file_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table_comment(
        'recommend_record',
        '推荐记录',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'recommend_record', type_='foreignkey')
    op.drop_constraint(None, 'recommend_record', type_='foreignkey')
    op.drop_constraint(None, 'recommend_record', type_='foreignkey')
    op.drop_index(op.f('ix_recommend_record_user_id'), table_name='recommend_record')
    op.drop_index(op.f('ix_recommend_record_job_id'), table_name='recommend_record')
    op.create_index(op.f('idx_recommend_user_id'), 'recommend_record', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_recommend_job_id'), 'recommend_record', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('recommend_record', 'is_invited',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('recommend_record', 'is_applied',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('recommend_record', 'is_clicked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('recommend_record', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'parse_task',
        '文档解析任务',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_parse_task_user_id'), table_name='parse_task')
    op.drop_index(op.f('ix_parse_task_file_id'), table_name='parse_task')
    op.create_index(op.f('idx_parse_task_user_id'), 'parse_task', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_parse_task_status'), 'parse_task', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_parse_task_file_id'), 'parse_task', ['file_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('parse_task', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态：WAITING/PARSING/SUCCESS/FAILED/REJECTED',
               existing_nullable=False,
               existing_server_default=sa.text("'WAITING'::character varying"))
    op.create_table_comment(
        'operation_log',
        '操作日志（AOP @OperationLog 落库）',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_operation_log_user_id'), table_name='operation_log')
    op.create_index(op.f('idx_operation_log_user_id'), 'operation_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_operation_log_module'), 'operation_log', ['module'], unique=False)
    op.create_table_comment(
        'occupation_role',
        '职业角色（后端开发/前端开发/测试工程师等）',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_occupation_role_name'), table_name='occupation_role')
    op.create_table_comment(
        'notification',
        '通知表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.create_index(op.f('idx_notification_user_id'), 'notification', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_notification_type'), 'notification', ['type'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_notification_is_read'), 'notification', ['is_read'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('notification', 'type',
               existing_type=sa.VARCHAR(length=30),
               comment='通知类型：APPLICATION/INTERVIEW_INVITE/SYSTEM',
               existing_nullable=False,
               existing_server_default=sa.text("'SYSTEM'::character varying"))
    op.alter_column('notification', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table_comment(
        'match_result',
        '匹配结果（懒计算 + 新鲜度缓存）',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'match_result', type_='foreignkey')
    op.drop_constraint(None, 'match_result', type_='foreignkey')
    op.drop_index(op.f('ix_match_result_resume_id'), table_name='match_result')
    op.drop_index(op.f('ix_match_result_job_id'), table_name='match_result')
    op.create_index(op.f('idx_match_result_score'), 'match_result', ['score'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_match_result_resume_job'), 'match_result', ['resume_id', 'job_id'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_match_result_resume_id'), 'match_result', ['resume_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_match_result_job_id'), 'match_result', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('match_result', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'job_skill',
        '岗位技能关联',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'job_skill', type_='foreignkey')
    op.drop_constraint(None, 'job_skill', type_='foreignkey')
    op.drop_index(op.f('ix_job_skill_skill_id'), table_name='job_skill')
    op.drop_index(op.f('ix_job_skill_job_id'), table_name='job_skill')
    op.create_index(op.f('idx_job_skill_skill_id'), 'job_skill', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_job_skill_job_id'), 'job_skill', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('job_skill', 'required_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='要求等级：MUST/NICE/BONUS',
               existing_server_default=sa.text("'NICE'::character varying"))
    op.alter_column('job_skill', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='重要度 1~5',
               existing_server_default=sa.text('3'))
    op.create_table_comment(
        'job',
        '岗位表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_index(op.f('ix_job_occupation_role_id'), table_name='job')
    op.drop_index(op.f('ix_job_company_id'), table_name='job')
    op.create_index(op.f('idx_job_status'), 'job', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_job_occupation_role_id'), 'job', ['occupation_role_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_job_company_id'), 'job', ['company_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_job_city'), 'job', ['city'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('job', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='岗位状态：OPEN/CLOSED/DRAFT',
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.alter_column('job', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='岗位来源：MANUAL手动/UPLOAD文件上传',
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.drop_column('job', 'job_category')
    op.drop_column('job', 'major')
    op.create_table_comment(
        'interview_session',
        '面试会话',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_interview_session_user_id'), table_name='interview_session')
    op.create_index(op.f('idx_interview_session_user_id'), 'interview_session', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_interview_session_status'), 'interview_session', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_interview_session_job_id'), 'interview_session', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('interview_session', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='会话状态：PENDING/IN_PROGRESS/COMPLETED/ABORTED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_table_comment(
        'interview_report',
        '面试报告',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_interview_report_session_id'), table_name='interview_report')
    op.create_index(op.f('idx_interview_report_session'), 'interview_report', ['session_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('interview_report', 'radar',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='五维雷达：communication/technical/problem_solving/culture_fit/depth',
               existing_nullable=True)
    op.alter_column('interview_report', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='综合评分 0~100',
               existing_nullable=True)
    op.create_table_comment(
        'interview_question',
        '面试问题',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_interview_question_session_id'), table_name='interview_question')
    op.create_index(op.f('idx_interview_question_session'), 'interview_question', ['session_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('interview_question', 'is_bank_visible',
               existing_type=sa.BOOLEAN(),
               comment='报告完成后是否题库可见',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('interview_question', 'question_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               comment='题型：TECHNICAL/BEHAVIORAL/SITUATIONAL/RESUME_BASED',
               existing_nullable=False)
    op.create_table_comment(
        'interview_answer',
        '用户面试回答',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_interview_answer_question_id'), table_name='interview_answer')
    op.create_index(op.f('idx_interview_answer_question'), 'interview_answer', ['question_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('interview_answer', 'ai_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='AI 评分 0~100',
               existing_nullable=True)
    op.create_table_comment(
        'company',
        '企业档案',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_user_id'), table_name='company')
    op.create_index(op.f('idx_company_user_id'), 'company', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_company_audit_status'), 'company', ['audit_status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('company', 'audit_status',
               existing_type=sa.VARCHAR(length=20),
               comment='审核状态：UNVERIFIED/PENDING/VERIFIED/REJECTED',
               existing_nullable=False,
               existing_server_default=sa.text("'UNVERIFIED'::character varying"))
    op.create_table_comment(
        'career_plan',
        '职业规划',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_career_plan_user_id'), table_name='career_plan')
    op.create_index(op.f('idx_career_plan_user_id'), 'career_plan', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.alter_column('career_plan', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='规划来源：INTERVIEW/PROACTIVE/RECOMMEND',
               existing_server_default=sa.text("'PROACTIVE'::character varying"))
    op.alter_column('career_plan', 'target_role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_ai_provider_provider_name'), table_name='ai_provider')
    op.create_index(op.f('idx_ai_provider_name'), 'ai_provider', ['provider_name'], unique=True)
    op.create_table('ai_chat_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chat_history_pkey')),
    comment='AI 对话历史'
    )
    op.create_index(op.f('idx_ai_chat_user_id'), 'ai_chat_history', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_ai_chat_module'), 'ai_chat_history', ['module'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('companies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('audit_status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('companies_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=True)
    op.create_table('occupation_role_skill',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('occupation_role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('requirement_level', sa.VARCHAR(length=20), server_default=sa.text("'NICE'::character varying"), autoincrement=False, nullable=False, comment='要求等级：MUST/NICE/BONUS'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('occupation_role_skill_pkey')),
    comment='职业角色技能关联'
    )
    op.create_index(op.f('idx_ors_skill_id'), 'occupation_role_skill', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index(op.f('idx_ors_role_id'), 'occupation_role_skill', ['occupation_role_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('login_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('login_log_pkey')),
    comment='登录日志（append-only）'
    )
    op.create_index(op.f('idx_login_log_user_id'), 'login_log', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###