"""create users and companies tables

Revision ID: 848a3822073a
Revises: dde25d9d8bd4
Create Date: 2026-07-07 10:07:36.002303+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '848a3822073a'
down_revision: Union[str, None] = 'dde25d9d8bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('audit_status', sa.String(length=16), nullable=False),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=True)
    op.drop_table('occupation_role')
    op.drop_index('idx_interview_session_job_id', table_name='interview_session', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_interview_session_status', table_name='interview_session', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_interview_session_user_id', table_name='interview_session', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('interview_session')
    op.drop_index('idx_company_audit_status', table_name='company', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_company_user_id', table_name='company', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('company')
    op.drop_index('idx_user_role', table_name='user', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_user_status', table_name='user', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_user_username', table_name='user', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('user')
    op.drop_index('idx_career_plan_user_id', table_name='career_plan', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('career_plan')
    op.drop_index('idx_skill_name', table_name='skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('skill')
    op.drop_index('idx_user_skill_skill_id', table_name='user_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_user_skill_user_id', table_name='user_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('user_skill')
    op.drop_index('idx_skill_relation_related', table_name='skill_relation', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_skill_relation_skill_id', table_name='skill_relation', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('skill_relation')
    op.drop_index('idx_parse_task_file_id', table_name='parse_task', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_parse_task_status', table_name='parse_task', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_parse_task_user_id', table_name='parse_task', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('parse_task')
    op.drop_index('idx_recommend_job_id', table_name='recommend_record', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_recommend_user_id', table_name='recommend_record', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('recommend_record')
    op.drop_index('idx_interview_question_session', table_name='interview_question', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('interview_question')
    op.drop_index('idx_ability_graph_user_id', table_name='ability_graph', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('ability_graph')
    op.drop_index('idx_resume_file_id', table_name='resume', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_resume_user_id', table_name='resume', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('resume')
    op.drop_index('idx_operation_log_module', table_name='operation_log')
    op.drop_index('idx_operation_log_user_id', table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index('idx_resume_opt_job_id', table_name='resume_optimization', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_resume_opt_resume_id', table_name='resume_optimization', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('resume_optimization')
    op.drop_index('idx_job_city', table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_job_company_id', table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_job_occupation_role_id', table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_job_status', table_name='job', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('job')
    op.drop_index('idx_ors_role_id', table_name='occupation_role_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_ors_skill_id', table_name='occupation_role_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('occupation_role_skill')
    op.drop_index('idx_upload_file_uploader', table_name='upload_file')
    op.drop_table('upload_file')
    op.drop_index('idx_login_log_user_id', table_name='login_log')
    op.drop_table('login_log')
    op.drop_index('idx_interview_answer_question', table_name='interview_answer', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('interview_answer')
    op.drop_index('idx_job_skill_job_id', table_name='job_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_job_skill_skill_id', table_name='job_skill', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('job_skill')
    op.drop_index('idx_user_profile_user_id', table_name='user_profile', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('user_profile')
    op.drop_index('idx_ai_chat_module', table_name='ai_chat_history', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_ai_chat_user_id', table_name='ai_chat_history', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('ai_chat_history')
    op.drop_index('idx_interview_report_session', table_name='interview_report', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('interview_report')
    op.drop_index('idx_skill_synonym_skill_id', table_name='skill_synonym', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_skill_synonym_synonym', table_name='skill_synonym', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('skill_synonym')
    op.drop_index('idx_match_result_job_id', table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_match_result_resume_id', table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_match_result_resume_job', table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_match_result_score', table_name='match_result', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('match_result')
    op.drop_index('idx_notification_is_read', table_name='notification', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_notification_type', table_name='notification', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_index('idx_notification_user_id', table_name='notification', postgresql_where="((deleted_at)::text = '0'::text)")
    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), server_default=sa.text("'SYSTEM'::character varying"), autoincrement=False, nullable=False, comment='通知类型：APPLICATION/INTERVIEW_INVITE/SYSTEM'),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='notification_pkey'),
    comment='通知表'
    )
    op.create_index('idx_notification_user_id', 'notification', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_notification_type', 'notification', ['type'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_notification_is_read', 'notification', ['is_read'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('match_result',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('match_detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='match_result_pkey'),
    comment='匹配结果（懒计算 + 新鲜度缓存）'
    )
    op.create_index('idx_match_result_score', 'match_result', ['score'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_match_result_resume_job', 'match_result', ['resume_id', 'job_id'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_match_result_resume_id', 'match_result', ['resume_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_match_result_job_id', 'match_result', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('skill_synonym',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('synonym', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skill_synonym_pkey'),
    comment='技能同义词（支撑三态合并）'
    )
    op.create_index('idx_skill_synonym_synonym', 'skill_synonym', ['synonym'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_skill_synonym_skill_id', 'skill_synonym', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('interview_report',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='综合评分 0~100'),
    sa.Column('radar', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='五维雷达：communication/technical/problem_solving/culture_fit/depth'),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='interview_report_pkey'),
    comment='面试报告'
    )
    op.create_index('idx_interview_report_session', 'interview_report', ['session_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('ai_chat_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ai_chat_history_pkey'),
    comment='AI 对话历史'
    )
    op.create_index('idx_ai_chat_user_id', 'ai_chat_history', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_ai_chat_module', 'ai_chat_history', ['module'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('user_profile',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('real_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('work_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expected_salary_min', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('expected_salary_max', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('expected_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('current_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_completeness', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='简历完成度 0~100'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_profile_pkey'),
    comment='求职者档案'
    )
    op.create_index('idx_user_profile_user_id', 'user_profile', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('job_skill',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('importance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('3'), autoincrement=False, nullable=True, comment='重要度 1~5'),
    sa.Column('required_level', sa.VARCHAR(length=20), server_default=sa.text("'NICE'::character varying"), autoincrement=False, nullable=True, comment='要求等级：MUST/NICE/BONUS'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='job_skill_pkey'),
    comment='岗位技能关联'
    )
    op.create_index('idx_job_skill_skill_id', 'job_skill', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_job_skill_job_id', 'job_skill', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('interview_answer',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='AI 评分 0~100'),
    sa.Column('ai_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('matched_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missed_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='interview_answer_pkey'),
    comment='用户面试回答'
    )
    op.create_index('idx_interview_answer_question', 'interview_answer', ['question_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('login_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='login_log_pkey'),
    comment='登录日志（append-only）'
    )
    op.create_index('idx_login_log_user_id', 'login_log', ['user_id'], unique=False)
    op.create_table('upload_file',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stored_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uploader_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='upload_file_pkey'),
    comment='文件本体表（单一事实源）'
    )
    op.create_index('idx_upload_file_uploader', 'upload_file', ['uploader_id'], unique=False)
    op.create_table('occupation_role_skill',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('occupation_role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('requirement_level', sa.VARCHAR(length=20), server_default=sa.text("'NICE'::character varying"), autoincrement=False, nullable=False, comment='要求等级：MUST/NICE/BONUS'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='occupation_role_skill_pkey'),
    comment='职业角色技能关联'
    )
    op.create_index('idx_ors_skill_id', 'occupation_role_skill', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_ors_role_id', 'occupation_role_skill', ['occupation_role_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('job',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('occupation_role_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salary_min', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_max', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('experience_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('education_requirement', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=20), server_default=sa.text("'FULL_TIME'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'OPEN'::character varying"), autoincrement=False, nullable=False, comment='岗位状态：OPEN/CLOSED/DRAFT'),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'MANUAL'::character varying"), autoincrement=False, nullable=False, comment='岗位来源：MANUAL手动/UPLOAD文件上传'),
    sa.Column('embedding_cache', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='job_pkey'),
    comment='岗位表'
    )
    op.create_index('idx_job_status', 'job', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_job_occupation_role_id', 'job', ['occupation_role_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_job_company_id', 'job', ['company_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_job_city', 'job', ['city'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('resume_optimization',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='resume_optimization_pkey'),
    comment='简历优化建议'
    )
    op.create_index('idx_resume_opt_resume_id', 'resume_optimization', ['resume_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_resume_opt_job_id', 'resume_optimization', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('operation_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='operation_log_pkey'),
    comment='操作日志（AOP @OperationLog 落库）'
    )
    op.create_index('idx_operation_log_user_id', 'operation_log', ['user_id'], unique=False)
    op.create_index('idx_operation_log_module', 'operation_log', ['module'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding_cache', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'NORMAL'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='resume_pkey'),
    comment='简历实体'
    )
    op.create_index('idx_resume_user_id', 'resume', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_resume_file_id', 'resume', ['file_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('ability_graph',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('graph_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ability_graph_pkey'),
    comment='能力图谱渲染缓存'
    )
    op.create_index('idx_ability_graph_user_id', 'ability_graph', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('interview_question',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='题型：TECHNICAL/BEHAVIORAL/SITUATIONAL/RESUME_BASED'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expected_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('order_no', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_bank_visible', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='报告完成后是否题库可见'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='interview_question_pkey'),
    comment='面试问题'
    )
    op.create_index('idx_interview_question_session', 'interview_question', ['session_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('recommend_record',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_clicked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_applied', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_invited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='recommend_record_pkey'),
    comment='推荐记录'
    )
    op.create_index('idx_recommend_user_id', 'recommend_record', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_recommend_job_id', 'recommend_record', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('parse_task',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'WAITING'::character varying"), autoincrement=False, nullable=False, comment='任务状态：WAITING/PARSING/SUCCESS/FAILED/REJECTED'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='parse_task_pkey'),
    comment='文档解析任务'
    )
    op.create_index('idx_parse_task_user_id', 'parse_task', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_parse_task_status', 'parse_task', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_parse_task_file_id', 'parse_task', ['file_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('skill_relation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('related_skill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='关系类型：PREREQUISITE/SIMILAR/INCLUDES/COMPLEMENTARY'),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skill_relation_pkey'),
    comment='技能关系边表'
    )
    op.create_index('idx_skill_relation_skill_id', 'skill_relation', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_skill_relation_related', 'skill_relation', ['related_skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('user_skill',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('proficiency_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_skill_pkey'),
    comment='用户技能关联'
    )
    op.create_index('idx_user_skill_user_id', 'user_skill', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_user_skill_skill_id', 'user_skill', ['skill_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('skill',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='技能领域：后端/前端/测试/运维/数据/通用'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False, comment='技能状态：ACTIVE/CANDIDATE/MERGED'),
    sa.Column('merge_target_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skill_pkey'),
    comment='技能字典'
    )
    op.create_index('idx_skill_name', 'skill', ['name'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('career_plan',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('plan_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'PROACTIVE'::character varying"), autoincrement=False, nullable=True, comment='规划来源：INTERVIEW/PROACTIVE/RECOMMEND'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='career_plan_pkey'),
    comment='职业规划'
    )
    op.create_index('idx_career_plan_user_id', 'career_plan', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'USER'::character varying"), autoincrement=False, nullable=False, comment='用户角色：ADMIN/USER/COMPANY'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'NORMAL'::character varying"), autoincrement=False, nullable=False, comment='账户状态：NORMAL/DISABLED/BANNED'),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False, comment='逻辑删除标记：0未删/1已删'),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    comment='用户主表'
    )
    op.create_index('idx_user_username', 'user', ['username'], unique=True, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_user_status', 'user', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_user_role', 'user', ['role'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('company',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('scale', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('audit_status', sa.VARCHAR(length=20), server_default=sa.text("'UNVERIFIED'::character varying"), autoincrement=False, nullable=False, comment='审核状态：UNVERIFIED/PENDING/VERIFIED/REJECTED'),
    sa.Column('audit_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='company_pkey'),
    comment='企业档案'
    )
    op.create_index('idx_company_user_id', 'company', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_company_audit_status', 'company', ['audit_status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('interview_session',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('occupation_role_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False, comment='会话状态：PENDING/IN_PROGRESS/COMPLETED/ABORTED'),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='interview_session_pkey'),
    comment='面试会话'
    )
    op.create_index('idx_interview_session_user_id', 'interview_session', ['user_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_interview_session_status', 'interview_session', ['status'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_index('idx_interview_session_job_id', 'interview_session', ['job_id'], unique=False, postgresql_where="((deleted_at)::text = '0'::text)")
    op.create_table('occupation_role',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.VARCHAR(length=1), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='occupation_role_pkey'),
    comment='职业角色（后端开发/前端开发/测试工程师等）'
    )
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###