-- H2 开发模式建表脚本

CREATE TABLE IF NOT EXISTS "user" (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(100),
    phone      VARCHAR(20),
    role       VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status     VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    avatar_url VARCHAR(500),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS company (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    company_name  VARCHAR(200) NOT NULL,
    industry      VARCHAR(100),
    scale         VARCHAR(50),
    website       VARCHAR(500),
    logo_url      VARCHAR(500),
    description   TEXT,
    address       VARCHAR(500),
    contact_name  VARCHAR(50),
    contact_phone VARCHAR(20),
    contact_email VARCHAR(100),
    audit_status  VARCHAR(20)  NOT NULL DEFAULT 'UNVERIFIED',
    audit_reason  TEXT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    VARCHAR(1)   NOT NULL DEFAULT '0'
);
