-- H2 开发模式建表脚本

CREATE TABLE IF NOT EXISTS "user" (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(100),
    phone      VARCHAR(20),
    role       VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status     VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    avatar_url VARCHAR(500),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS user_profile (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT       NOT NULL,
    real_name             VARCHAR(50),
    gender                VARCHAR(10),
    birth_date            DATE,
    education             VARCHAR(20),
    school                VARCHAR(100),
    major                 VARCHAR(100),
    work_years            INT,
    expected_salary_min   DECIMAL(12,2),
    expected_salary_max   DECIMAL(12,2),
    expected_city         VARCHAR(100),
    current_city          VARCHAR(100),
    bio                   TEXT,
    profile_completeness  INT DEFAULT 0,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at            VARCHAR(1) NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS company (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    company_name  VARCHAR(200) NOT NULL,
    industry      VARCHAR(100),
    scale         VARCHAR(50),
    website       VARCHAR(500),
    logo_url      VARCHAR(500),
    description   TEXT,
    address       VARCHAR(500),
    contact_name  VARCHAR(50),
    contact_phone VARCHAR(20),
    contact_email VARCHAR(100),
    audit_status  VARCHAR(20)  NOT NULL DEFAULT 'UNVERIFIED',
    audit_reason  TEXT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS upload_file (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(255) NOT NULL,
    path          VARCHAR(500) NOT NULL,
    size          BIGINT       NOT NULL,
    mime_type     VARCHAR(100),
    uploader_id   BIGINT       NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS resume (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    file_id         BIGINT,
    title           VARCHAR(200),
    content_text    TEXT,
    embedding_cache CLOB,
    status          VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS parse_task (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'WAITING',
    result     CLOB,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS skill (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    category        VARCHAR(50),
    description     TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    merge_target_id BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS skill_synonym (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id   BIGINT       NOT NULL,
    synonym    VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS skill_relation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id         BIGINT       NOT NULL,
    related_skill_id BIGINT       NOT NULL,
    relation_type    VARCHAR(30)  NOT NULL,
    weight           DOUBLE       DEFAULT 1.0,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at       VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS occupation_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description TEXT,
    category    VARCHAR(50),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS job (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT       NOT NULL,
    occupation_role_id   BIGINT,
    title                VARCHAR(200) NOT NULL,
    description          TEXT,
    requirements         TEXT,
    salary_min           DECIMAL(12,2),
    salary_max           DECIMAL(12,2),
    city                 VARCHAR(100),
    experience_min       INT,
    education_requirement VARCHAR(20),
    job_type             VARCHAR(20)  NOT NULL DEFAULT 'FULL_TIME',
    status               VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    source               VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',
    embedding_cache      CLOB,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at           VARCHAR(1)   NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS job_skill (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id         BIGINT       NOT NULL,
    skill_id       BIGINT       NOT NULL,
    importance     DOUBLE       DEFAULT 3.0,
    required_level VARCHAR(20)  DEFAULT 'NICE',
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     VARCHAR(1)   NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS user_skill (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT  NOT NULL,
    skill_id          BIGINT  NOT NULL,
    proficiency_level DOUBLE  DEFAULT 0,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        VARCHAR(1) NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS operation_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    module     VARCHAR(50),
    action     VARCHAR(100),
    detail     CLOB,
    ip         VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at VARCHAR(1) NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS match_result (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id    BIGINT NOT NULL,
    job_id       BIGINT NOT NULL,
    score        DOUBLE DEFAULT 0,
    match_detail CLOB,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at   VARCHAR(1) NOT NULL DEFAULT '0'
);